apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-worker-app
  labels:
    {{- include "maybe-worker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "maybe-worker.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "maybe-worker.labels" . | nindent 8 }}
    spec:
      containers:
      - name: maybe
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["bundle", "exec", "sidekiq"]
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: RAILS_ENV
          value: {{ .Values.maybe.env.RAILS_ENV }}
        - name: DATABASE_URL
          value: "postgresql://maybe:maybe@{{ .Release.Name }}-postgres:5432/maybe?sslmode=disable"
        - name: REDIS_URL
          value: "redis://{{ .Release.Name }}-redis:6379/0"
        - name: PLAID_CLIENT_ID
          valueFrom:
           secretKeyRef:
            name: maybe-secrets
            key: plaid-client-id
        - name: PLAID_SECRET
          valueFrom:
           secretKeyRef:
            name: maybe-secrets
            key: plaid-client-secret
        - name: PLAID_ENV
          value: {{ .Values.maybe.env.PLAID_ENV }}
        - name: SELF_HOSTED
          value: "{{ .Values.maybe.env.SELF_HOSTED }}"
        - name: RAILS_FORCE_SSL
          value: "{{ .Values.maybe.env.RAILS_FORCE_SSL }}"
        - name: RAILS_ASSUME_SSL
          value: "{{ .Values.maybe.env.RAILS_ASSUME_SSL }}"
        - name: GOOD_JOB_EXECUTION_MODE
          value: {{ .Values.maybe.env.GOOD_JOB_EXECUTION_MODE }}
        - name: SECRET_KEY_BASE
          valueFrom:
           secretKeyRef:
            name: maybe-secrets
            key: secret-key-base
        - name: OPENAI_ACCESS_TOKEN
          valueFrom:
           secretKeyRef:
            name: maybe-secrets
            key: openai-api-key
        - name: SYNTH_API_KEY
          valueFrom:
           secretKeyRef:
            name: maybe-secrets
            key: synth-api-key
        - name: FMP_API_KEY
          valueFrom:
           secretKeyRef:
            name: maybe-secrets
            key: fmp-api-key
