replicaCount: 1

image:
  repository: junzhutx/maybe-homelab
  tag: "0.2.7" # Or pin to "v0.2.0-rc2"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  hostname: maybe.lan
  ingressClassName: nginx # Adjust if using a different ingress controller

maybe:
  env:
    RAILS_ENV: production
    PLAID_CLIENT_ID: "" # Add your Plaid creds
    PLAID_SECRET: ""
    PLAID_ENV: "sandbox" # Or "production"
    SELF_HOSTED: "true"
    RAILS_FORCE_SSL: "false"
    RAILS_ASSUME_SSL: "false"
    GOOD_JOB_EXECUTION_MODE: "async"

postgres:
  enabled: true
  image: postgres:16
  username: maybe
  password: maybe
  database: maybe

redis:
  enabled: true
  image: redis:7